# Generated by Django 3.2.9 on 2021-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
